name: SurvivalGamesV3
main: SurvivalGamesV3\SurvivalGamesV3
version: 3.0.3
api: [1.0.0, 2.0.0]
author: ImagicalGamer


commands:
    sg:
        usage: /sg create
        description: SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands
