name: SurvivalGamesV3
main: SurvivalGamesV3\SurvivalGamesV3
version: 4.0
api: [1.0.0, 2.0.0, 3.0.0]
author: ImagicalGamer


commands:
    sg:
        usage: /sg
        description: A full list of SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands
